import { Country } from "../types/countries";

export const countries: Country[] = [
   {
      name: "Afghanistan",
      code: "AF",
      timeZone: "Asia/Kabul",
      phoneNumberExtension: "93",
   },
   {
      name: "Åland Islands",
      code: "AX",
      timeZone: "Europe/Mariehamn",
      phoneNumberExtension: "358",
   },
   {
      name: "Albania",
      code: "AL",
      timeZone: "Europe/Tirane",
      phoneNumberExtension: "355",
   },
   {
      name: "Algeria",
      code: "DZ",
      timeZone: "Africa/Algiers",
      phoneNumberExtension: "213",
   },
   {
      name: "United States of America",
      code: "US",
      timeZone: "America/New_York",
      phoneNumberExtension: "1",
      phoneNumberFormat: "(XXX)XXX-XXXX",
   },
   {
      name: "American Samoa",
      code: "AS",
      timeZone: "Pacific/Pago_Pago",
      phoneNumberExtension: "1",
      phoneNumberFormat: "(XXX)XXX-XXXX",
   },
   {
      name: "AndorrA",
      code: "AD",
      timeZone: "Europe/Andorra",
      phoneNumberExtension: "376",
   },
   {
      name: "Angola",
      code: "AO",
      timeZone: "Africa/Luanda",
      phoneNumberExtension: "244",
   },
   {
      name: "Anguilla",
      code: "AI",
      timeZone: "America/Anguilla",
      phoneNumberExtension: "1",
      phoneNumberFormat: "(XXX)XXX-XXXX",
   },
   {
      name: "Antarctica",
      code: "AQ",
      timeZone: "Antarctica/Casey",
      phoneNumberExtension: "672",
   },
   {
      name: "Antigua and Barbuda",
      code: "AG",
      timeZone: "America/Antigua",
      phoneNumberExtension: "1",
      phoneNumberFormat: "(XXX)XXX-XXXX",
   },
   {
      name: "Argentina",
      code: "AR",
      timeZone: "America/Argentina/Buenos_Aires",
      phoneNumberExtension: "54",
   },
   {
      name: "Armenia",
      code: "AM",
      timeZone: "Asia/Yerevan",
      phoneNumberExtension: "374",
   },
   {
      name: "Aruba",
      code: "AW",
      timeZone: "America/Aruba",
      phoneNumberExtension: "297",
   },
   {
      name: "Australia",
      code: "AU",
      timeZone: "Australia/Sydney",
      phoneNumberExtension: "61",
   },
   {
      name: "Austria",
      code: "AT",
      timeZone: "Europe/Vienna",
      phoneNumberExtension: "43",
   },
   {
      name: "Azerbaijan",
      code: "AZ",
      timeZone: "Asia/Baku",
      phoneNumberExtension: "994",
   },
   {
      name: "Bahamas",
      code: "BS",
      timeZone: "America/Nassau",
      phoneNumberExtension: "1",
      phoneNumberFormat: "(XXX)XXX-XXXX",
   },
   {
      name: "Bahrain",
      code: "BH",
      timeZone: "Asia/Bahrain",
      phoneNumberExtension: "973",
   },
   {
      name: "Bangladesh",
      code: "BD",
      timeZone: "Asia/Dhaka",
      phoneNumberExtension: "880",
   },
   {
      name: "Barbados",
      code: "BB",
      timeZone: "America/Barbados",
      phoneNumberExtension: "1",
      phoneNumberFormat: "(XXX)XXX-XXXX",
   },
   {
      name: "Belarus",
      code: "BY",
      timeZone: "Europe/Minsk",
      phoneNumberExtension: "375",
   },
   {
      name: "Belgium",
      code: "BE",
      timeZone: "Europe/Brussels",
      phoneNumberExtension: "32",
   },
   {
      name: "Belize",
      code: "BZ",
      timeZone: "America/Belize",
      phoneNumberExtension: "501",
   },
   {
      name: "Benin",
      code: "BJ",
      timeZone: "Africa/Porto-Novo",
      phoneNumberExtension: "229",
   },
   {
      name: "Bermuda",
      code: "BM",
      timeZone: "Atlantic/Bermuda",
      phoneNumberExtension: "1",
      phoneNumberFormat: "(XXX)XXX-XXXX",
   },
   {
      name: "Bhutan",
      code: "BT",
      timeZone: "Asia/Thimphu",
      phoneNumberExtension: "975",
   },
   {
      name: "Bolivia",
      code: "BO",
      timeZone: "America/La_Paz",
      phoneNumberExtension: "591",
   },
   {
      name: "Bosnia and Herzegovina",
      code: "BA",
      timeZone: "Europe/Sarajevo",
      phoneNumberExtension: "387",
   },
   {
      name: "Botswana",
      code: "BW",
      timeZone: "Africa/Gaborone",
      phoneNumberExtension: "267",
   },
   {
      name: "Bouvet Island",
      code: "BV",
      timeZone: "Europe/Oslo",
      phoneNumberExtension: "47",
   },
   {
      name: "Brazil",
      code: "BR",
      timeZone: "America/Sao_Paulo",
      phoneNumberExtension: "55",
   },
   {
      name: "British Indian Ocean Territory",
      code: "IO",
      timeZone: "Indian/Chagos",
      phoneNumberExtension: "246",
   },
   {
      name: "Brunei Darussalam",
      code: "BN",
      timeZone: "Asia/Brunei",
      phoneNumberExtension: "673",
   },
   {
      name: "Bulgaria",
      code: "BG",
      timeZone: "Europe/Sofia",
      phoneNumberExtension: "359",
      phoneNumberFormat: "XX XXX XXXX",
   },
   {
      name: "Burkina Faso",
      code: "BF",
      timeZone: "Africa/Ouagadougou",
      phoneNumberExtension: "226",
   },
   {
      name: "Burundi",
      code: "BI",
      timeZone: "Africa/Bujumbura",
      phoneNumberExtension: "257",
   },
   {
      name: "Cambodia",
      code: "KH",
      timeZone: "Asia/Phnom_Penh",
      phoneNumberExtension: "855",
   },
   {
      name: "Cameroon",
      code: "CM",
      timeZone: "Africa/Douala",
      phoneNumberExtension: "237",
   },
   {
      name: "Canada",
      code: "CA",
      timeZone: "America/Toronto",
      phoneNumberExtension: "1",
      phoneNumberFormat: "(XXX)XXX-XXXX",
   },
   {
      name: "Cape Verde",
      code: "CV",
      timeZone: "Atlantic/Cape_Verde",
      phoneNumberExtension: "238",
   },
   {
      name: "Cayman Islands",
      code: "KY",
      timeZone: "America/Cayman",
      phoneNumberExtension: "1",
      phoneNumberFormat: "(XXX)XXX-XXXX",
   },
   {
      name: "Central African Republic",
      code: "CF",
      timeZone: "Africa/Bangui",
      phoneNumberExtension: "236",
   },
   {
      name: "Chad",
      code: "TD",
      timeZone: "Africa/Ndjamena",
      phoneNumberExtension: "235",
   },
   {
      name: "Chile",
      code: "CL",
      timeZone: "America/Santiago",
      phoneNumberExtension: "56",
   },
   {
      name: "China",
      code: "CN",
      timeZone: "Asia/Shanghai",
      phoneNumberExtension: "86",
   },
   {
      name: "Christmas Island",
      code: "CX",
      timeZone: "Indian/Christmas",
      phoneNumberExtension: "61",
   },
   {
      name: "Cocos (Keeling) Islands",
      code: "CC",
      timeZone: "Indian/Cocos",
      phoneNumberExtension: "61",
   },
   {
      name: "Colombia",
      code: "CO",
      timeZone: "America/Bogota",
      phoneNumberExtension: "57",
   },
   {
      name: "Comoros",
      code: "KM",
      timeZone: "Indian/Comoro",
      phoneNumberExtension: "269",
   },
   {
      name: "Congo",
      code: "CG",
      timeZone: "Africa/Brazzaville",
      phoneNumberExtension: "242",
   },
   {
      name: "Congo, The Democratic Republic of the",
      code: "CD",
      timeZone: "Africa/Kinshasa",
      phoneNumberExtension: "243",
   },
   {
      name: "Cook Islands",
      code: "CK",
      timeZone: "Pacific/Rarotonga",
      phoneNumberExtension: "682",
   },
   {
      name: "Costa Rica",
      code: "CR",
      timeZone: "America/Costa_Rica",
      phoneNumberExtension: "506",
   },
   {
      name: "Cote D'Ivoire",
      code: "CI",
      timeZone: "Africa/Abidjan",
      phoneNumberExtension: "225",
   },
   {
      name: "Croatia",
      code: "HR",
      timeZone: "Europe/Zagreb",
      phoneNumberExtension: "385",
   },
   {
      name: "Cuba",
      code: "CU",
      timeZone: "America/Havana",
      phoneNumberExtension: "53",
   },
   {
      name: "Cyprus",
      code: "CY",
      timeZone: "Asia/Nicosia",
      phoneNumberExtension: "357",
   },
   {
      name: "Czech Republic",
      code: "CZ",
      timeZone: "Europe/Prague",
      phoneNumberExtension: "420",
   },
   {
      name: "Denmark",
      code: "DK",
      timeZone: "Europe/Copenhagen",
      phoneNumberExtension: "45",
   },
   {
      name: "Djibouti",
      code: "DJ",
      timeZone: "Africa/Djibouti",
      phoneNumberExtension: "253",
   },
   {
      name: "Dominica",
      code: "DM",
      timeZone: "America/Dominica",
      phoneNumberExtension: "1",
      phoneNumberFormat: "(XXX)XXX-XXXX",
   },
   {
      name: "Dominican Republic",
      code: "DO",
      timeZone: "America/Santo_Domingo",
      phoneNumberExtension: "1",
      phoneNumberFormat: "(XXX)XXX-XXXX",
   },
   {
      name: "Ecuador",
      code: "EC",
      timeZone: "America/Guayaquil",
      phoneNumberExtension: "593",
   },
   {
      name: "Egypt",
      code: "EG",
      timeZone: "Africa/Cairo",
      phoneNumberExtension: "20",
   },
   {
      name: "El Salvador",
      code: "SV",
      timeZone: "America/El_Salvador",
      phoneNumberExtension: "503",
   },
   {
      name: "Equatorial Guinea",
      code: "GQ",
      timeZone: "Africa/Malabo",
      phoneNumberExtension: "240",
   },
   {
      name: "Eritrea",
      code: "ER",
      timeZone: "Africa/Asmara",
      phoneNumberExtension: "291",
   },
   {
      name: "Estonia",
      code: "EE",
      timeZone: "Europe/Tallinn",
      phoneNumberExtension: "372",
   },
   {
      name: "Ethiopia",
      code: "ET",
      timeZone: "Africa/Addis_Ababa",
      phoneNumberExtension: "251",
   },
   {
      name: "Falkland Islands (Malvinas)",
      code: "FK",
      timeZone: "Atlantic/Stanley",
      phoneNumberExtension: "500",
   },
   {
      name: "Faroe Islands",
      code: "FO",
      timeZone: "Atlantic/Faroe",
      phoneNumberExtension: "298",
   },
   {
      name: "Fiji",
      code: "FJ",
      timeZone: "Pacific/Fiji",
      phoneNumberExtension: "679",
   },
   {
      name: "Finland",
      code: "FI",
      timeZone: "Europe/Helsinki",
      phoneNumberExtension: "358",
   },
   {
      name: "France",
      code: "FR",
      timeZone: "Europe/Paris",
      phoneNumberExtension: "33",
   },
   {
      name: "French Guiana",
      code: "GF",
      timeZone: "America/Cayenne",
      phoneNumberExtension: "594",
   },
   {
      name: "French Polynesia",
      code: "PF",
      timeZone: "Pacific/Tahiti",
      phoneNumberExtension: "689",
   },
   {
      name: "French Southern Territories",
      code: "TF",
      timeZone: "Indian/Kerguelen",
      phoneNumberExtension: "262",
   },
   {
      name: "Gabon",
      code: "GA",
      timeZone: "Africa/Libreville",
      phoneNumberExtension: "241",
   },
   {
      name: "Gambia",
      code: "GM",
      timeZone: "Africa/Banjul",
      phoneNumberExtension: "220",
   },
   {
      name: "Georgia",
      code: "GE",
      timeZone: "Asia/Tbilisi",
      phoneNumberExtension: "995",
   },
   {
      name: "Germany",
      code: "DE",
      timeZone: "Europe/Berlin",
      phoneNumberExtension: "49",
      phoneNumberFormat: "XXXX XXXXXX",
   },
   {
      name: "Ghana",
      code: "GH",
      timeZone: "Africa/Accra",
      phoneNumberExtension: "233",
   },
   {
      name: "Gibraltar",
      code: "GI",
      timeZone: "Europe/Gibraltar",
      phoneNumberExtension: "350",
   },
   {
      name: "Greece",
      code: "GR",
      timeZone: "Europe/Athens",
      phoneNumberExtension: "30",
   },
   {
      name: "Greenland",
      code: "GL",
      timeZone: "America/Godthab",
      phoneNumberExtension: "299",
   },
   {
      name: "Grenada",
      code: "GD",
      timeZone: "America/Grenada",
      phoneNumberExtension: "1",
      phoneNumberFormat: "(XXX)XXX-XXXX",
   },
   {
      name: "Guadeloupe",
      code: "GP",
      timeZone: "America/Guadeloupe",
      phoneNumberExtension: "590",
   },
   {
      name: "Guam",
      code: "GU",
      timeZone: "Pacific/Guam",
      phoneNumberExtension: "1",
      phoneNumberFormat: "(XXX)XXX-XXXX",
   },
   {
      name: "Guatemala",
      code: "GT",
      timeZone: "America/Guatemala",
      phoneNumberExtension: "502",
   },
   {
      name: "United Kingdom",
      code: "GB",
      timeZone: "Europe/London",
      phoneNumberExtension: "44",
      phoneNumberFormat: "XX XXXX XXXX",
   },
   {
      name: "Guernsey",
      code: "GG",
      timeZone: "Europe/Guernsey",
      phoneNumberExtension: "44",
      phoneNumberFormat: "XX XXXX XXXX",
   },
   {
      name: "Guinea",
      code: "GN",
      timeZone: "Africa/Conakry",
      phoneNumberExtension: "224",
   },
   {
      name: "Guinea-Bissau",
      code: "GW",
      timeZone: "Africa/Bissau",
      phoneNumberExtension: "245",
   },
   {
      name: "Guyana",
      code: "GY",
      timeZone: "America/Guyana",
      phoneNumberExtension: "592",
   },
   {
      name: "Haiti",
      code: "HT",
      timeZone: "America/Port-au-Prince",
      phoneNumberExtension: "509",
   },
   {
      name: "Heard Island and Mcdonald Islands",
      code: "HM",
      timeZone: "Indian/Kerguelen",
      phoneNumberExtension: "672",
   },
   {
      name: "Holy See (Vatican City State)",
      code: "VA",
      timeZone: "Europe/Vatican",
      phoneNumberExtension: "379",
   },
   {
      name: "Honduras",
      code: "HN",
      timeZone: "America/Tegucigalpa",
      phoneNumberExtension: "504",
   },
   {
      name: "Hong Kong",
      code: "HK",
      timeZone: "Asia/Hong_Kong",
      phoneNumberExtension: "852",
   },
   {
      name: "Hungary",
      code: "HU",
      timeZone: "Europe/Budapest",
      phoneNumberExtension: "36",
   },
   {
      name: "Iceland",
      code: "IS",
      timeZone: "Atlantic/Reykjavik",
      phoneNumberExtension: "354",
   },
   {
      name: "India",
      code: "IN",
      timeZone: "Asia/Kolkata",
      phoneNumberExtension: "91",
   },
   {
      name: "Indonesia",
      code: "ID",
      timeZone: "Asia/Jakarta",
      phoneNumberExtension: "62",
   },
   {
      name: "Iran, Islamic Republic Of",
      code: "IR",
      timeZone: "Asia/Tehran",
      phoneNumberExtension: "98",
   },
   {
      name: "Iraq",
      code: "IQ",
      timeZone: "Asia/Baghdad",
      phoneNumberExtension: "964",
   },
   {
      name: "Ireland",
      code: "IE",
      timeZone: "Europe/Dublin",
      phoneNumberExtension: "353",
   },
   {
      name: "Israel",
      code: "IL",
      timeZone: "Asia/Jerusalem",
      phoneNumberExtension: "972",
   },
   {
      name: "Italy",
      code: "IT",
      timeZone: "Europe/Rome",
      phoneNumberExtension: "39",
   },
   {
      name: "Jamaica",
      code: "JM",
      timeZone: "America/Jamaica",
      phoneNumberExtension: "1",
      phoneNumberFormat: "(XXX)XXX-XXXX",
   },
   {
      name: "Japan",
      code: "JP",
      timeZone: "Asia/Tokyo",
      phoneNumberExtension: "81",
   },
   {
      name: "Jersey",
      code: "JE",
      timeZone: "Europe/Jersey",
      phoneNumberExtension: "44",
      phoneNumberFormat: "XX XXXX XXXX",
   },
   {
      name: "Jordan",
      code: "JO",
      timeZone: "Asia/Amman",
      phoneNumberExtension: "962",
   },
   {
      name: "Kazakhstan",
      code: "KZ",
      timeZone: "Asia/Almaty",
      phoneNumberExtension: "7",
   },
   {
      name: "Kenya",
      code: "KE",
      timeZone: "Africa/Nairobi",
      phoneNumberExtension: "254",
   },
   {
      name: "Kiribati",
      code: "KI",
      timeZone: "Pacific/Tarawa",
      phoneNumberExtension: "686",
   },
   {
      name: "Korea, Democratic People's Republic of (North Korea)",
      code: "KP",
      timeZone: "Asia/Pyongyang",
      phoneNumberExtension: "850",
   },
   {
      name: "Korea, Republic of (South Korea)",
      code: "KR",
      timeZone: "Asia/Seoul",
      phoneNumberExtension: "82",
   },
   {
      name: "Kuwait",
      code: "KW",
      timeZone: "Asia/Kuwait",
      phoneNumberExtension: "965",
   },
   {
      name: "Kyrgyzstan",
      code: "KG",
      timeZone: "Asia/Bishkek",
      phoneNumberExtension: "996",
   },
   {
      name: "Lao People's Democratic Republic",
      code: "LA",
      timeZone: "Asia/Vientiane",
      phoneNumberExtension: "856",
   },
   {
      name: "Latvia",
      code: "LV",
      timeZone: "Europe/Riga",
      phoneNumberExtension: "371",
   },
   {
      name: "Lebanon",
      code: "LB",
      timeZone: "Asia/Beirut",
      phoneNumberExtension: "961",
   },
   {
      name: "Lesotho",
      code: "LS",
      timeZone: "Africa/Maseru",
      phoneNumberExtension: "266",
   },
   {
      name: "Liberia",
      code: "LR",
      timeZone: "Africa/Monrovia",
      phoneNumberExtension: "231",
   },
   {
      name: "Libyan Arab Jamahiriya",
      code: "LY",
      timeZone: "Africa/Tripoli",
      phoneNumberExtension: "218",
   },
   {
      name: "Liechtenstein",
      code: "LI",
      timeZone: "Europe/Vaduz",
      phoneNumberExtension: "423",
   },
   {
      name: "Lithuania",
      code: "LT",
      timeZone: "Europe/Vilnius",
      phoneNumberExtension: "370",
   },
   {
      name: "Luxembourg",
      code: "LU",
      timeZone: "Europe/Luxembourg",
      phoneNumberExtension: "352",
   },
   {
      name: "Macao",
      code: "MO",
      timeZone: "Asia/Macau",
      phoneNumberExtension: "853",
   },
   {
      name: "Macedonia, The Former Yugoslav Republic of",
      code: "MK",
      timeZone: "Europe/Skopje",
      phoneNumberExtension: "389",
   },
   {
      name: "Madagascar",
      code: "MG",
      timeZone: "Indian/Antananarivo",
      phoneNumberExtension: "261",
   },
   {
      name: "Malawi",
      code: "MW",
      timeZone: "Africa/Blantyre",
      phoneNumberExtension: "265",
   },
   {
      name: "Malaysia",
      code: "MY",
      timeZone: "Asia/Kuala_Lumpur",
      phoneNumberExtension: "60",
   },
   {
      name: "Maldives",
      code: "MV",
      timeZone: "Indian/Maldives",
      phoneNumberExtension: "960",
   },
   {
      name: "Mali",
      code: "ML",
      timeZone: "Africa/Bamako",
      phoneNumberExtension: "223",
   },
   {
      name: "Malta",
      code: "MT",
      timeZone: "Europe/Malta",
      phoneNumberExtension: "356",
   },
   {
      name: "Marshall Islands",
      code: "MH",
      timeZone: "Pacific/Majuro",
      phoneNumberExtension: "692",
   },
   {
      name: "Martinique",
      code: "MQ",
      timeZone: "America/Martinique",
      phoneNumberExtension: "596",
   },
   {
      name: "Mauritania",
      code: "MR",
      timeZone: "Africa/Nouakchott",
      phoneNumberExtension: "222",
   },
   {
      name: "Mauritius",
      code: "MU",
      timeZone: "Indian/Mauritius",
      phoneNumberExtension: "230",
   },
   {
      name: "Mayotte",
      code: "YT",
      timeZone: "Indian/Mayotte",
      phoneNumberExtension: "262",
   },
   {
      name: "Mexico",
      code: "MX",
      timeZone: "America/Mexico_City",
      phoneNumberExtension: "52",
   },
   {
      name: "Micronesia, Federated States of",
      code: "FM",
      timeZone: "Pacific/Chuuk",
      phoneNumberExtension: "691",
   },
   {
      name: "Moldova, Republic of",
      code: "MD",
      timeZone: "Europe/Chisinau",
      phoneNumberExtension: "373",
   },
   {
      name: "Monaco",
      code: "MC",
      timeZone: "Europe/Monaco",
      phoneNumberExtension: "377",
   },
   {
      name: "Mongolia",
      code: "MN",
      timeZone: "Asia/Ulaanbaatar",
      phoneNumberExtension: "976",
   },
   {
      name: "Montserrat",
      code: "MS",
      timeZone: "America/Montserrat",
      phoneNumberExtension: "1",
      phoneNumberFormat: "(XXX)XXX-XXXX",
   },
   {
      name: "Morocco",
      code: "MA",
      timeZone: "Africa/Casablanca",
      phoneNumberExtension: "212",
   },
   {
      name: "Mozambique",
      code: "MZ",
      timeZone: "Africa/Maputo",
      phoneNumberExtension: "258",
   },
   {
      name: "Myanmar",
      code: "MM",
      timeZone: "Asia/Yangon",
      phoneNumberExtension: "95",
   },
   {
      name: "Namibia",
      code: "NA",
      timeZone: "Africa/Windhoek",
      phoneNumberExtension: "264",
   },
   {
      name: "Nauru",
      code: "NR",
      timeZone: "Pacific/Nauru",
      phoneNumberExtension: "674",
   },
   {
      name: "Nepal",
      code: "NP",
      timeZone: "Asia/Kathmandu",
      phoneNumberExtension: "977",
   },
   {
      name: "Netherlands",
      code: "NL",
      timeZone: "Europe/Amsterdam",
      phoneNumberExtension: "31",
   },
   {
      name: "New Caledonia",
      code: "NC",
      timeZone: "Pacific/Noumea",
      phoneNumberExtension: "687",
   },
   {
      name: "New Zealand",
      code: "NZ",
      timeZone: "Pacific/Auckland",
      phoneNumberExtension: "64",
   },
   {
      name: "Nicaragua",
      code: "NI",
      timeZone: "America/Managua",
      phoneNumberExtension: "505",
   },
   {
      name: "Niger",
      code: "NE",
      timeZone: "Africa/Niamey",
      phoneNumberExtension: "227",
   },
   {
      name: "Nigeria",
      code: "NG",
      timeZone: "Africa/Lagos",
      phoneNumberExtension: "234",
   },
   {
      name: "Niue",
      code: "NU",
      timeZone: "Pacific/Niue",
      phoneNumberExtension: "683",
   },
   {
      name: "Norfolk Island",
      code: "NF",
      timeZone: "Pacific/Norfolk",
      phoneNumberExtension: "672",
   },
   {
      name: "Northern Mariana Islands",
      code: "MP",
      timeZone: "Pacific/Saipan",
      phoneNumberExtension: "1",
      phoneNumberFormat: "(XXX)XXX-XXXX",
   },
   {
      name: "Norway",
      code: "NO",
      timeZone: "Europe/Oslo",
      phoneNumberExtension: "47",
   },
   {
      name: "Oman",
      code: "OM",
      timeZone: "Asia/Muscat",
      phoneNumberExtension: "968",
   },
   {
      name: "Pakistan",
      code: "PK",
      timeZone: "Asia/Karachi",
      phoneNumberExtension: "92",
   },
   {
      name: "Palau",
      code: "PW",
      timeZone: "Pacific/Palau",
      phoneNumberExtension: "680",
   },
   {
      name: "Palestinian Territory, Occupied",
      code: "PS",
      timeZone: "Asia/Hebron",
      phoneNumberExtension: "970",
   },
   {
      name: "Panama",
      code: "PA",
      timeZone: "America/Panama",
      phoneNumberExtension: "507",
   },
   {
      name: "Papua New Guinea",
      code: "PG",
      timeZone: "Pacific/Port_Moresby",
      phoneNumberExtension: "675",
   },
   {
      name: "Paraguay",
      code: "PY",
      timeZone: "America/Asuncion",
      phoneNumberExtension: "595",
   },
   {
      name: "Peru",
      code: "PE",
      timeZone: "America/Lima",
      phoneNumberExtension: "51",
   },
   {
      name: "Philippines",
      code: "PH",
      timeZone: "Asia/Manila",
      phoneNumberExtension: "63",
   },
   {
      name: "Pitcairn",
      code: "PN",
      timeZone: "Pacific/Pitcairn",
      phoneNumberExtension: "64",
   },
   {
      name: "Poland",
      code: "PL",
      timeZone: "Europe/Warsaw",
      phoneNumberExtension: "48",
   },
   {
      name: "Portugal",
      code: "PT",
      timeZone: "Europe/Lisbon",
      phoneNumberExtension: "351",
   },
   {
      name: "Puerto Rico",
      code: "PR",
      timeZone: "America/Puerto_Rico",
      phoneNumberExtension: "1",
      phoneNumberFormat: "(XXX)XXX-XXXX",
   },
   {
      name: "Qatar",
      code: "QA",
      timeZone: "Asia/Qatar",
      phoneNumberExtension: "974",
   },
   {
      name: "Reunion",
      code: "RE",
      timeZone: "Indian/Reunion",
      phoneNumberExtension: "262",
   },
   {
      name: "Romania",
      code: "RO",
      timeZone: "Europe/Bucharest",
      phoneNumberExtension: "40",
   },
   {
      name: "Russian Federation",
      code: "RU",
      timeZone: "Europe/Moscow",
      phoneNumberExtension: "7",
   },
   {
      name: "RWANDA",
      code: "RW",
      timeZone: "Africa/Kigali",
      phoneNumberExtension: "250",
   },
   {
      name: "Saint Helena",
      code: "SH",
      timeZone: "Atlantic/St_Helena",
      phoneNumberExtension: "290",
   },
   {
      name: "Saint Kitts and Nevis",
      code: "KN",
      timeZone: "America/St_Kitts",
      phoneNumberExtension: "1",
      phoneNumberFormat: "(XXX)XXX-XXXX",
   },
   {
      name: "Saint Lucia",
      code: "LC",
      timeZone: "America/St_Lucia",
      phoneNumberExtension: "1",
      phoneNumberFormat: "(XXX)XXX-XXXX",
   },
   {
      name: "Saint Pierre and Miquelon",
      code: "PM",
      timeZone: "America/Miquelon",
      phoneNumberExtension: "508",
   },
   {
      name: "Saint Vincent and the Grenadines",
      code: "VC",
      timeZone: "America/St_Vincent",
      phoneNumberExtension: "1",
      phoneNumberFormat: "(XXX)XXX-XXXX",
   },
   {
      name: "Samoa",
      code: "WS",
      timeZone: "Pacific/Apia",
      phoneNumberExtension: "685",
   },
   {
      name: "San Marino",
      code: "SM",
      timeZone: "Europe/San_Marino",
      phoneNumberExtension: "378",
   },
   {
      name: "Sao Tome and Principe",
      code: "ST",
      timeZone: "Africa/Sao_Tome",
      phoneNumberExtension: "239",
   },
   {
      name: "Saudi Arabia",
      code: "SA",
      timeZone: "Asia/Riyadh",
      phoneNumberExtension: "966",
   },
   {
      name: "Senegal",
      code: "SN",
      timeZone: "Africa/Dakar",
      phoneNumberExtension: "221",
   },
   {
      name: "Republic of Serbia",
      code: "RS",
      timeZone: "Europe/Belgrade",
      phoneNumberExtension: "381",
   },
   {
      name: "Seychelles",
      code: "SC",
      timeZone: "Indian/Mahe",
      phoneNumberExtension: "248",
   },
   {
      name: "Sierra Leone",
      code: "SL",
      timeZone: "Africa/Freetown",
      phoneNumberExtension: "232",
   },
   {
      name: "Singapore",
      code: "SG",
      timeZone: "Asia/Singapore",
      phoneNumberExtension: "65",
   },
   {
      name: "Slovakia",
      code: "SK",
      timeZone: "Europe/Bratislava",
      phoneNumberExtension: "421",
   },
   {
      name: "Slovenia",
      code: "SI",
      timeZone: "Europe/Ljubljana",
      phoneNumberExtension: "386",
   },
   {
      name: "Solomon Islands",
      code: "SB",
      timeZone: "Pacific/Guadalcanal",
      phoneNumberExtension: "677",
   },
   {
      name: "Somalia",
      code: "SO",
      timeZone: "Africa/Mogadishu",
      phoneNumberExtension: "252",
   },
   {
      name: "South Africa",
      code: "ZA",
      timeZone: "Africa/Johannesburg",
      phoneNumberExtension: "27",
   },
   {
      name: "South Georgia and the South Sandwich Islands",
      code: "GS",
      timeZone: "Atlantic/South_Georgia",
      phoneNumberExtension: "500",
   },
   {
      name: "Spain",
      code: "ES",
      timeZone: "Europe/Madrid",
      phoneNumberExtension: "34",
   },
   {
      name: "Sri Lanka",
      code: "LK",
      timeZone: "Asia/Colombo",
      phoneNumberExtension: "94",
   },
   {
      name: "Sudan",
      code: "SD",
      timeZone: "Africa/Khartoum",
      phoneNumberExtension: "249",
   },
   {
      name: "Suriname",
      code: "SR",
      timeZone: "America/Paramaribo",
      phoneNumberExtension: "597",
   },
   {
      name: "Svalbard and Jan Mayen",
      code: "SJ",
      timeZone: "Arctic/Longyearbyen",
      phoneNumberExtension: "47",
   },
   {
      name: "Swaziland",
      code: "SZ",
      timeZone: "Africa/Mbabane",
      phoneNumberExtension: "268",
   },
   {
      name: "Sweden",
      code: "SE",
      timeZone: "Europe/Stockholm",
      phoneNumberExtension: "46",
   },
   {
      name: "Switzerland",
      code: "CH",
      timeZone: "Europe/Zurich",
      phoneNumberExtension: "41",
   },
   {
      name: "Syrian Arab Republic",
      code: "SY",
      timeZone: "Asia/Damascus",
      phoneNumberExtension: "963",
   },
   {
      name: "Taiwan, Province of China",
      code: "TW",
      timeZone: "Asia/Taipei",
      phoneNumberExtension: "886",
   },
   {
      name: "Tajikistan",
      code: "TJ",
      timeZone: "Asia/Dushanbe",
      phoneNumberExtension: "992",
   },
   {
      name: "Tanzania, United Republic of",
      code: "TZ",
      timeZone: "Africa/Dar_es_Salaam",
      phoneNumberExtension: "255",
   },
   {
      name: "Thailand",
      code: "TH",
      timeZone: "Asia/Bangkok",
      phoneNumberExtension: "66",
   },
   {
      name: "Timor-Leste",
      code: "TL",
      timeZone: "Asia/Dili",
      phoneNumberExtension: "670",
   },
   {
      name: "Togo",
      code: "TG",
      timeZone: "Africa/Lome",
      phoneNumberExtension: "228",
   },
   {
      name: "Tokelau",
      code: "TK",
      timeZone: "Pacific/Fakaofo",
      phoneNumberExtension: "690",
   },
   {
      name: "Tonga",
      code: "TO",
      timeZone: "Pacific/Tongatapu",
      phoneNumberExtension: "676",
   },
   {
      name: "Trinidad and Tobago",
      code: "TT",
      timeZone: "America/Port_of_Spain",
      phoneNumberExtension: "1",
      phoneNumberFormat: "(XXX)XXX-XXXX",
   },
   {
      name: "Tunisia",
      code: "TN",
      timeZone: "Africa/Tunis",
      phoneNumberExtension: "216",
   },
   {
      name: "Turkey",
      code: "TR",
      timeZone: "Europe/Istanbul",
      phoneNumberExtension: "90",
   },
   {
      name: "Turkmenistan",
      code: "TM",
      timeZone: "Asia/Ashgabat",
      phoneNumberExtension: "993",
   },
   {
      name: "Turks and Caicos Islands",
      code: "TC",
      timeZone: "America/Grand_Turk",
      phoneNumberExtension: "1",
      phoneNumberFormat: "(XXX)XXX-XXXX",
   },
   {
      name: "Tuvalu",
      code: "TV",
      timeZone: "Pacific/Funafuti",
      phoneNumberExtension: "688",
   },
   {
      name: "Uganda",
      code: "UG",
      timeZone: "Africa/Kampala",
      phoneNumberExtension: "256",
   },
   {
      name: "Ukraine",
      code: "UA",
      timeZone: "Europe/Kiev",
      phoneNumberExtension: "380",
   },
   {
      name: "United Arab Emirates",
      code: "AE",
      timeZone: "Asia/Dubai",
      phoneNumberExtension: "971",
   },
   {
      name: "United States Minor Outlying Islands",
      code: "UM",
      timeZone: "Pacific/Midway",
      phoneNumberExtension: "1",
      phoneNumberFormat: "(XXX)XXX-XXXX",
   },
   {
      name: "Uruguay",
      code: "UY",
      timeZone: "America/Montevideo",
      phoneNumberExtension: "598",
   },
   {
      name: "Uzbekistan",
      code: "UZ",
      timeZone: "Asia/Tashkent",
      phoneNumberExtension: "998",
   },
   {
      name: "Vanuatu",
      code: "VU",
      timeZone: "Pacific/Efate",
      phoneNumberExtension: "678",
   },
   {
      name: "Venezuela",
      code: "VE",
      timeZone: "America/Caracas",
      phoneNumberExtension: "58",
   },
   {
      name: "Viet Nam",
      code: "VN",
      timeZone: "Asia/Ho_Chi_Minh",
      phoneNumberExtension: "84",
   },
   {
      name: "Virgin Islands, British",
      code: "VG",
      timeZone: "America/Tortola",
      phoneNumberExtension: "1",
      phoneNumberFormat: "(XXX)XXX-XXXX",
   },
   {
      name: "Virgin Islands, U.S.",
      code: "VI",
      timeZone: "America/St_Thomas",
      phoneNumberExtension: "1",
      phoneNumberFormat: "(XXX)XXX-XXXX",
   },
   {
      name: "Wallis and Futuna",
      code: "WF",
      timeZone: "Pacific/Wallis",
      phoneNumberExtension: "681",
   },
   {
      name: "Western Sahara",
      code: "EH",
      timeZone: "Africa/El_Aaiun",
      phoneNumberExtension: "212",
   },
   {
      name: "Yemen",
      code: "YE",
      timeZone: "Asia/Aden",
      phoneNumberExtension: "967",
   },
   {
      name: "Zambia",
      code: "ZM",
      timeZone: "Africa/Lusaka",
      phoneNumberExtension: "260",
   },
   {
      name: "Zimbabwe",
      code: "ZW",
      timeZone: "Africa/Harare",
      phoneNumberExtension: "263",
   },
] as const;
