import { BetterHtmlPlugin } from "./plugin";

export type ComponentStyle = React.CSSProperties;
export type ComponentHoverStyle = {
   [CSSProperty in keyof ComponentStyle as `${CSSProperty & string}Hover`]: ComponentStyle[CSSProperty];
};

export type ComponentMarginProps = Pick<
   ComponentStyle,
   "margin" | "marginTop" | "marginBottom" | "marginLeft" | "marginRight" | "marginBlock" | "marginInline"
>;
export type ComponentPaddingProps = Pick<
   ComponentStyle,
   "padding" | "paddingTop" | "paddingBottom" | "paddingLeft" | "paddingRight" | "paddingBlock" | "paddingInline"
>;

export type ComponentPropWithRef<ComponentRef, ComponentProps> = ComponentProps & { ref?: React.Ref<ComponentRef> };
export type ComponentPropWithPlugin<ComponentProps> = ComponentProps & {
   plugin: BetterHtmlPlugin;
};

export type AllHtmlTags =
   | "a"
   | "abbr"
   | "address"
   | "area"
   | "article"
   | "aside"
   | "audio"
   | "b"
   | "base"
   | "bdi"
   | "bdo"
   | "big"
   | "blockquote"
   | "body"
   | "br"
   | "button"
   | "canvas"
   | "caption"
   | "center"
   | "cite"
   | "code"
   | "col"
   | "colgroup"
   | "data"
   | "datalist"
   | "dd"
   | "del"
   | "details"
   | "dfn"
   | "dialog"
   | "div"
   | "dl"
   | "dt"
   | "em"
   | "embed"
   | "fieldset"
   | "figcaption"
   | "figure"
   | "footer"
   | "form"
   | "h1"
   | "h2"
   | "h3"
   | "h4"
   | "h5"
   | "h6"
   | "head"
   | "header"
   | "hgroup"
   | "hr"
   | "html"
   | "i"
   | "iframe"
   | "img"
   | "input"
   | "ins"
   | "kbd"
   | "keygen"
   | "label"
   | "legend"
   | "li"
   | "link"
   | "main"
   | "map"
   | "mark"
   | "menu"
   | "menuitem"
   | "meta"
   | "meter"
   | "nav"
   | "noindex"
   | "noscript"
   | "object"
   | "ol"
   | "optgroup"
   | "option"
   | "output"
   | "p"
   | "param"
   | "picture"
   | "pre"
   | "progress"
   | "q"
   | "rp"
   | "rt"
   | "ruby"
   | "s"
   | "samp"
   | "search"
   | "slot"
   | "script"
   | "section"
   | "select"
   | "small"
   | "source"
   | "span"
   | "strong"
   | "style"
   | "sub"
   | "summary"
   | "sup"
   | "table"
   | "template"
   | "tbody"
   | "td"
   | "textarea"
   | "tfoot"
   | "th"
   | "thead"
   | "time"
   | "title"
   | "tr"
   | "track"
   | "u"
   | "ul"
   | "var"
   | "video"
   | "wbr"
   | "webview";
